version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backendsevice
    build:
      context: .
      dockerfile: ./Dockerfile
  client: 
    image: client
    build: 
      context: ./frontendservice
      dockerfile: Dockerfile
